### ISSUE TITLE
add `vanity_url `to `/v1/content` output

### ISSUE THREAD

**Issue by kmasiello** [posit-dev/posit-sdk-py#174] opened 2024-04-16 19:22 UTC
Replicating https://github.com/rstudio/connectapi/issues/219 issue from `connectapi` here.

The output of `content.find()` should also include the vanity URL, not just the content_url.

**Comment by tdstein** [comment] 2024-04-18 15:00
Thanks @kmasiello - closing this as a duplicate of #175

**Closed by tdstein** 2024-04-18 15:00 UTC
